In [1]:
import numpy as np
import pandas as pd
import random
from tqdm import tqdm
from math import *
from matplotlib import pyplot as plt
from ahm import *
%matplotlib inline
%load_ext autoreload
%autoreload 2

## load data

In [3]:
item_attribute = pd.read_csv('data/item_attribute.csv', header=None)
# Qmat = pd.read_excel('data/Qmatrix_koh.xlsx', header=None).drop(columns=[7,8])
# Qmat.to_csv('data/item_attribute.csv', index=None, header=None)
item_attribute = np.array(item_attribute)
item_attribute

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 1, 0]])

In [2]:
real_response = np.array(pd.read_excel('data/Qdata.xlsx').drop(columns=['ID','area','sex','total']))

/Users/yyoo/opt/anaconda3/lib/python3.7/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


------------------------------------------------------------

In [4]:
attribute_num = 7

In [5]:
graph = Graph(attribute_num)

In [6]:
graph.add_edge(0,1)
graph.add_edge(0,2)
graph.add_edge(0,4)
graph.add_edge(1,3)
graph.add_edge(1,5)
graph.add_edge(2,3)
graph.add_edge(2,6)

In [7]:
A = graph.adjacency_matrix
print(A)

[[0, 1, 1, 0, 1, 0, 0], [0, 0, 0, 1, 0, 1, 0], [0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]


In [8]:
R = calc_reachability(A)
print(R)

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [9]:
# Q = calc_Q(R, False)
# print(Q.shape)
# Qr = calc_Q(R, True)
# print(Qr.shape)

In [10]:
Q = calc_Q(R)
print(Q.shape)
print(Q)

(26, 7)
[[1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0]
 [1 0 1 0 0 0 0]
 [1 0 1 0 0 0 1]
 [1 0 1 0 1 0 0]
 [1 0 1 0 1 0 1]
 [1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0]
 [1 1 0 0 1 0 0]
 [1 1 0 0 1 1 0]
 [1 1 1 0 0 0 0]
 [1 1 1 0 0 0 1]
 [1 1 1 0 0 1 0]
 [1 1 1 0 0 1 1]
 [1 1 1 0 1 0 0]
 [1 1 1 0 1 0 1]
 [1 1 1 0 1 1 0]
 [1 1 1 0 1 1 1]
 [1 1 1 1 0 0 0]
 [1 1 1 1 0 0 1]
 [1 1 1 1 0 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]
 [1 1 1 1 1 0 1]
 [1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1]]


----------------------------------------------------------------------------------

In [11]:
ideal_responses = calc_ideal_responses(Q)

---------------------------------------------------------------

In [12]:
all_hamming_dists = list()

for item in range(Q.shape[0]):
    all_hamming_dists.append(calc_hamming_dist(item_attribute, Q[item]))
all_hamming_dists[0]

[0,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 2,
 2,
 3,
 4,
 3,
 3,
 1,
 4,
 3,
 5,
 4,
 2,
 2,
 4,
 2,
 3,
 1,
 2,
 5,
 2,
 2,
 4]

-----------------------------------------------------------

In [13]:
iteration = 1500

In [14]:
cost = calc_cost(real_response, ideal_responses, Q, get_index(Q, all_hamming_dists, iteration), iteration)

100%|██████████| 1500/1500 [05:58<00:00,  4.18it/s]


In [15]:
cum_std = [np.std(cost[:i]) for i in tqdm(range(1, iteration + 1))]
cum_mean = [np.mean(cost[:i]) for i in tqdm(range(1, iteration + 1))]

100%|██████████| 1500/1500 [00:00<00:00, 28478.69it/s]


In [16]:
cum_mean[-1]

0.19284686245177546